name: RWS submission checks
on: 
  pull_request:
    branches:
      - main
jobs:
  PR-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Check Rakuten site
        run:  python check_sites.py -p https://rakuten.co.jp > result.txt
      - name: "Read the result"
        id: read_results
        uses: andstor/file-reader-action@v1
        with:
          path: "results.txt"
      - name: "File contents"
        env:
            CONTENTS: ${{ steps.read_results.outputs.contents }}
        run: echo "$CONTENTS"
      - name: Create Comment
        if: steps.read_results.outputs.contents != 'success'
        run: |
         echo "It appears you have failed some tests. Here are your results:" > message.txt
         cat results.txt >> message.txt
      - name: Comment if sucess
        if: steps.read_results.outputs.contents == 'success'
        run: echo "Looks like you've passed all of the checks!" >> message.txt
      - name: Write Comment on PR
        uses: mshick/add-pr-comment@v2
        with:   
          message-path: "message.txt" 
          refresh-message-position: true
      - name: Fail or Succeed
        if: steps.read_results.outputs.contents != 'success'
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('This run has failed. Check `File Contents` to see why.')
        